export const PROVINCES_REQUEST = "PROVINCES_REQUEST"
export const PROVINCES_SUCCESS = "PROVINCES_SUCCESS"
export const PROVINCES_FAIL = "PROVINCES_FAIL"

export const PROVINCE_REQUEST = "PROVINCE_REQUEST"
export const PROVINCE_SUCCESS = "PROVINCE_SUCCESS"
export const PROVINCE_FAIL = "PROVINCE_FAIL"

export const DISTRICT_REQUEST = "DISTRICT_REQUEST"
export const DISTRICT_SUCCESS = "DISTRICT_SUCCESS"
export const DISTRICT_FAIL = "DISTRICT_FAIL"
