export const PRODUCT_LIST_NEW_REQUEST = "PRODUCT_LIST_NEW_REQUEST"
export const PRODUCT_LIST_NEW_SUCCESS = "PRODUCT_LIST_NEW_SUCCESS"
export const PRODUCT_LIST_NEW_FAIL = "PRODUCT_LIST_NEW_FAIL"

export const PRODUCT_LIST_HOT_REQUEST = "PRODUCT_LIST_HOT_REQUEST"
export const PRODUCT_LIST_HOT_SUCCESS = "PRODUCT_LIST_HOT_SUCCESS"
export const PRODUCT_LIST_HOT_FAIL = "PRODUCT_LIST_HOT_FAIL"

export const PRODUCT_LIST_RELATED_REQUEST = "PRODUCT_LIST_RELATED_REQUEST"
export const PRODUCT_LIST_RELATED_SUCCESS = "PRODUCT_LIST_RELATED_SUCCESS"
export const PRODUCT_LIST_RELATED_FAIL = "PRODUCT_LIST_RELATED_FAIL"

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL"

export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST"
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL"

export const PRODUCT_LIST_SUGGESTION_REQUEST = "PRODUCT_LIST_SUGGESTION_REQUEST"
export const PRODUCT_LIST_SUGGESTION_SUCCESS = "PRODUCT_LIST_SUGGESTION_SUCCESS"
export const PRODUCT_LIST_SUGGESTION_FAIL = "PRODUCT_LIST_SUGGESTION_FAIL"
